// Export (JSON / SRT / VTT / TXT / ASS) and import (SRT / VTT) of captions.
// Exported times are composition times (0 = composition start), which is what
// a render of the composition will use.

import { DEFAULT_ANIMATION, DEFAULT_SEGMENT, DEFAULT_STYLE } from "./defaults";
import { tokenize, views } from "./edit";
import { newProjectId, serializeProject } from "./project";
import { newCaptionId, joinWords } from "./segment";
import { formatClock } from "./timing";
import type { Project, Word } from "./types";

export type ExportFormat = "json" | "srt" | "vtt" | "txt" | "ass";

export const EXPORT_FORMATS: { id: ExportFormat; label: string; ext: string; hint: string }[] = [
  { id: "json", label: "AutoCaption Project (JSON)", ext: "json", hint: "Full word timing. Re-import without transcribing." },
  { id: "srt", label: "SubRip (SRT)", ext: "srt", hint: "Works with YouTube, Premiere, Resolve" },
  { id: "vtt", label: "WebVTT (VTT)", ext: "vtt", hint: "For web players" },
  { id: "ass", label: "Advanced SubStation (ASS)", ext: "ass", hint: "Keeps fonts, colours and karaoke timing" },
  { id: "txt", label: "Plain transcript (TXT)", ext: "txt", hint: "Text only" },
];

function captionText(p: Project, lines: Word[][]): string {
  const noSpaces = !!p.transcription.noSpaces;
  const t = lines.map((l) => joinWords(l, noSpaces)).join("\n");
  return p.style.allCaps ? t.toLocaleUpperCase() : t;
}

export function toSRT(p: Project): string {
  return views(p).map((v, i) =>
    `${i + 1}\n${formatClock(Math.max(0, v.start), ",")} --> ${formatClock(Math.max(0, v.end), ",")}\n${captionText(p, v.lines)}\n`,
  ).join("\n");
}

export function toVTT(p: Project): string {
  const body = views(p).map((v) =>
    `${formatClock(Math.max(0, v.start))} --> ${formatClock(Math.max(0, v.end))}\n${captionText(p, v.lines)}\n`,
  ).join("\n");
  return `WEBVTT\n\n${body}`;
}

export function toTXT(p: Project): string {
  const noSpaces = !!p.transcription.noSpaces;
  const out: string[] = [];
  let para: string[] = [];
  let lastEnd = -Infinity;
  for (const w of p.words) {
    if (para.length && w.start - lastEnd > 1.5) {
      out.push(para.join(noSpaces ? "" : " "));
      para = [];
    }
    para.push(w.text);
    lastEnd = w.end;
  }
  if (para.length) out.push(para.join(noSpaces ? "" : " "));
  return out.join("\n\n") + "\n";
}

/** "#RRGGBB" + opacity -> ASS "&HAABBGGRR" (alpha 00 = opaque). */
export function assColor(hex: string, opacity = 1): string {
  const m = /^#?([0-9a-f]{6})$/i.exec(hex.trim());
  const rgb = m ? m[1] : "FFFFFF";
  const a = Math.round((1 - Math.max(0, Math.min(1, opacity))) * 255);
  const h = (n: number) => n.toString(16).toUpperCase().padStart(2, "0");
  return `&H${h(a)}${rgb.slice(4, 6)}${rgb.slice(2, 4)}${rgb.slice(0, 2)}`.toUpperCase();
}

function assTime(t: number): string {
  const cs = Math.max(0, Math.round(t * 100));
  const h = Math.floor(cs / 360000);
  const m = Math.floor((cs % 360000) / 6000);
  const s = Math.floor((cs % 6000) / 100);
  return `${h}:${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}.${String(cs % 100).padStart(2, "0")}`;
}

function assEscape(t: string): string {
  return t.replace(/\\/g, "\\\\").replace(/\{/g, "\\{").replace(/\}/g, "\\}");
}

export function toASS(p: Project): string {
  const s = p.style;
  const W = Math.round(p.source.width || 1920);
  const H = Math.round(p.source.height || 1080);
  const align = s.align === "left" ? 1 : s.align === "right" ? 3 : 2; // bottom row
  const marginV = Math.max(0, Math.round(H * (1 - s.positionY) - s.fontSize * 0.6));
  const karaoke = p.animation.preset === "karaoke" || p.animation.preset === "highlight";
  const primary = karaoke ? assColor(p.animation.highlightColor) : assColor(s.fill);
  const secondary = assColor(s.fill);
  const border = s.backgroundEnabled ? 3 : 1;
  const outlineColor = s.backgroundEnabled ? assColor(s.background, s.backgroundOpacity) : assColor(s.stroke);
  const outline = s.backgroundEnabled ? Math.round(s.padding / 3) : s.strokeEnabled ? Math.max(0, s.strokeWidth / 2) : 0;
  const shadow = s.shadowEnabled ? Math.max(1, Math.round(s.shadowDistance / 2)) : 0;
  const header = [
    "[Script Info]",
    "; Generated by AutoCaption AE",
    "ScriptType: v4.00+",
    `PlayResX: ${W}`,
    `PlayResY: ${H}`,
    "WrapStyle: 2",
    "ScaledBorderAndShadow: yes",
    "",
    "[V4+ Styles]",
    "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding",
    `Style: Default,${s.fontFamily},${Math.round(s.fontSize)},${primary},${secondary},${outlineColor},${assColor(s.shadowColor, s.shadowOpacity)},${/bold|black|heavy/i.test(s.font) ? -1 : 0},0,0,0,${s.scale},${s.scale},${(s.tracking / 1000) * s.fontSize},0,${border},${outline},${shadow},${align},40,40,${marginV},1`,
    "",
    "[Events]",
    "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
  ];
  const noSpaces = !!p.transcription.noSpaces;
  const events = views(p).map((v) => {
    let text: string;
    if (karaoke) {
      // \k durations in centiseconds, from the real word starts
      const parts: string[] = [];
      let cursor = v.start;
      v.lines.forEach((line, li) => {
        line.forEach((w, wi) => {
          const lead = Math.max(0, Math.round((w.start - cursor) * 100));
          if (lead > 0) parts.push(`{\\k${lead}}`);
          const dur = Math.max(1, Math.round((w.end - Math.max(cursor, w.start)) * 100));
          const word = s.allCaps ? w.text.toLocaleUpperCase() : w.text;
          parts.push(`{\\k${dur}}${assEscape(word)}${wi < line.length - 1 && !noSpaces ? " " : ""}`);
          cursor = Math.max(cursor, w.end);
        });
        if (li < v.lines.length - 1) parts.push("\\N");
      });
      text = parts.join("");
    } else {
      text = assEscape(captionText(p, v.lines)).replace(/\n/g, "\\N");
    }
    const fade = p.animation.preset === "fade" ? `{\\fad(${Math.round(p.animation.duration * 1000)},${p.animation.animateOut ? Math.round(p.animation.duration * 1000) : 0})}` : "";
    return `Dialogue: 0,${assTime(v.start)},${assTime(v.end)},Default,,0,0,0,,${fade}${text}`;
  });
  return [...header, ...events, ""].join("\n");
}

export function exportProject(p: Project, format: ExportFormat): string {
  switch (format) {
    case "json": return serializeProject(p);
    case "srt": return toSRT(p);
    case "vtt": return toVTT(p);
    case "txt": return toTXT(p);
    case "ass": return toASS(p);
  }
}

// ----------------------------------------------------------------- import
export interface ImportedCue {
  start: number;
  end: number;
  text: string;
}

function cueTime(s: string): number {
  const m = /^(?:(\d+):)?(\d{1,2}):(\d{2})[.,](\d{1,3})$/.exec(s.trim());
  if (!m) return NaN;
  return (m[1] ? +m[1] * 3600 : 0) + +m[2] * 60 + +m[3] + +m[4].padEnd(3, "0") / 1000;
}

/** Parses both SRT and WebVTT cue blocks. */
export function parseCues(text: string): ImportedCue[] {
  const blocks = text.replace(/^﻿/, "").replace(/\r\n?/g, "\n").split(/\n{2,}/);
  const cues: ImportedCue[] = [];
  for (const block of blocks) {
    const lines = block.split("\n").filter((l) => l.trim() !== "");
    const ti = lines.findIndex((l) => l.includes("-->"));
    if (ti < 0) continue;
    const [a, b] = lines[ti].split("-->");
    const start = cueTime(a);
    const end = cueTime(b.trim().split(/\s+/)[0]);
    const body = lines.slice(ti + 1).join(" ").replace(/<[^>]+>/g, "").replace(/\{\\[^}]*\}/g, "").trim();
    if (Number.isFinite(start) && Number.isFinite(end) && end > start && body) cues.push({ start, end, text: body });
  }
  return cues;
}

/**
 * Build a project from subtitle cues. Subtitle files carry no word timing, so
 * words are placed proportionally inside their cue and marked "inferred"
 * (the UI offers "Align to audio" to replace them with real alignment).
 */
export function projectFromCues(cues: ImportedCue[], name: string, base?: Project): Project {
  const words: Word[] = [];
  const captions: Project["captions"] = [];
  let n = 0;
  for (const cue of cues) {
    const toks = tokenize(cue.text, false);
    const total = toks.reduce((a, t) => a + Math.max(1, t.length), 0);
    let acc = 0;
    const ids: string[] = [];
    for (const t of toks) {
      const s = cue.start + ((cue.end - cue.start) * acc) / total;
      acc += Math.max(1, t.length);
      const e = cue.start + ((cue.end - cue.start) * acc) / total;
      n += 1;
      const id = `i${n}`;
      words.push({ id, text: t, start: Math.round(s * 1000) / 1000, end: Math.round(e * 1000) / 1000, timingSource: "inferred" });
      ids.push(id);
    }
    if (ids.length) captions.push({ id: newCaptionId(), wordIds: ids, locked: true, start: cue.start, end: cue.end });
  }
  const now = new Date().toISOString();
  const end = cues.length ? cues[cues.length - 1].end : 0;
  return {
    schemaVersion: 1,
    app: { name: "AutoCaption AE", version: base?.app.version ?? "1.0.0" },
    project: { id: newProjectId(), name, createdAt: now, updatedAt: now },
    source: base?.source ?? {
      composition: "Imported", layers: [], layerType: "unknown", fps: 30, frameDuration: 1 / 30, compStartTime: 0,
      compDuration: end + 1, width: 1920, height: 1080, audioOffset: 0, audioDuration: end, mapping: "import",
    },
    transcription: { language: base?.transcription.language ?? "en", model: "import", aligned: false, warnings: [
      { code: "IMPORTED", message: "Imported subtitles have caption timing only. Word timing is estimated." },
    ] },
    sourceWords: words.map((w) => ({ ...w })),
    words,
    captions,
    segment: base?.segment ?? { ...DEFAULT_SEGMENT },
    style: base?.style ?? { ...DEFAULT_STYLE },
    animation: base?.animation ?? { ...DEFAULT_ANIMATION },
  };
}
